export const API_ROOT = (process.env.NODE_ENV === "production") ? process.env.API_URL || '/api/v1' : '/api/v1'

//Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

//User
export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAILURE = 'USER_FAILURE'
export const USER_ADD = 'USER_ADD'
export const USER_REMOVE = 'USER_REMOVE'
export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_SUCCESS = 'USERS_SUCCESS'
export const USERS_FAILURE = 'USERS_FAILURE'
export const RESEND_REQUEST = 'RESEND_REQUEST'
export const RESEND_SUCCESS = 'RESEND_SUCCESS'
export const RESEND_FAILURE = 'RESEND_FAILURE'

//Venues
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const ATTEND_REQUEST = 'ATTEND_REQUEST'
export const ATTEND_SUCCESS = 'ATTEND_SUCCESS'
export const ATTEND_FAILURE = 'ATTEND_FAILURE'
export const UNATTEND_REQUEST = 'UNATTEND_REQUEST'
export const UNATTEND_SUCCESS = 'UNATTEND_SUCCESS'
export const UNATTEND_FAILURE = 'UNATTEND_FAILURE'
export const VENUES_REQUEST = 'VENUES_REQUEST'
export const VENUES_SUCCESS = 'VENUES_SUCCESS'
export const VENUES_FAILURE = 'VENUES_FAILURE'
export const VENUE_UPDATE = 'VENUE_UPDATE'

//Flash
export const RESET_MESSAGE = 'RESET_MESSAGE'
export const SET_MESSAGE = 'SET_MESSAGE'
